name: Run Pytest

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: "postgres2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Failure Log
        if: failure()
        run: echo "1つ前のstepは失敗しました"

      - name: Print DB_USER
        run: echo "DB_USER -> ${{ env.DB_USER }}"

      - name: Print secrets
        run: echo "SUPU_API_KEY -> ${{ secrets.SUPU_API_KEY }}"

      - name: Get time
        id: get_time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

      - name: Print github output
        run: echo "1つ前のstepの出力は${{ steps.get_time.output.time}}です"